"use strict";

const video=document.getElementById("video"),canvas=document.getElementById("canvas"),ctx=canvas.getContext("2d");
const statusEl=document.getElementById("status"),startButton=document.getElementById("start"),calibrarButton=document.getElementById("calibrar"),pedrinhaButton=document.getElementById("pedrinha"),limparButton=document.getElementById("limpar"),cameraBox=document.querySelector(".camera");
const work=document.createElement("canvas"),wctx=work.getContext("2d",{willReadFrequently:true});
let W=240,H=430,stream=null,cameraAtiva=false,modo="parado",copos=[],alvoCopoId=null,raf=0,last=0,busy=false,cvReady=false,prevGray=null;
let pedra={active:false,visible:false,x:0,y:0,template:null,size:25,lastScore:0,lost:0};
const MAX_PIXELS=120000,PROCESS_MS=55;
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function status(t){statusEl.textContent=t;}
function ensureCV(){return new Promise((resolve,reject)=>{if(window.cv&&cv.Mat){cvReady=true;resolve();return;}let tries=0;const t=setInterval(()=>{tries++;if(window.cv&&cv.Mat){clearInterval(t);cvReady=true;resolve();}else if(tries>160){clearInterval(t);reject(new Error("OpenCV não carregou"));}},100);});}
function dims(){if(!video.videoWidth)return;const s=Math.min(1,Math.sqrt(MAX_PIXELS/(video.videoWidth*video.videoHeight)));W=Math.max(180,Math.round(video.videoWidth*s));H=Math.max(180,Math.round(video.videoHeight*s));work.width=W;work.height=H;canvas.width=video.videoWidth;canvas.height=video.videoHeight;cameraBox.style.aspectRatio=`${video.videoWidth}/${video.videoHeight}`;}
function grab(){wctx.drawImage(video,0,0,W,H);const img=wctx.getImageData(0,0,W,H);const rgba=cv.matFromImageData(img),gray=new cv.Mat();cv.cvtColor(rgba,gray,cv.COLOR_RGBA2GRAY);rgba.delete();return gray;}
function pointMat(points){const m=new cv.Mat(points.length,1,cv.CV_32FC2);for(let i=0;i<points.length;i++){m.data32F[i*2]=points[i][0];m.data32F[i*2+1]=points[i][1];}return m;}
function seedPoints(gray,c){const pts=[];const x0=clamp(Math.round(c.x-c.boxW*.5),0,W-1),x1=clamp(Math.round(c.x+c.boxW*.5),0,W);const y0=clamp(Math.round(c.y-c.boxH*.28),0,H-1),y1=clamp(Math.round(c.y+c.boxH*.46),0,H);const roi=new cv.Mat();gray.roi(new cv.Rect(x0,y0,Math.max(1,x1-x0),Math.max(1,y1-y0))).copyTo(roi);const p=new cv.Mat();cv.goodFeaturesToTrack(roi,p,70,0.015,5);for(let i=0;i<p.rows;i++)pts.push([p.data32F[i*2]+x0,p.data32F[i*2+1]+y0]);roi.delete();p.delete();return pts;}
function initializeTrack(x,y,id,gray){const boxW=clamp(Math.round(W*.30),52,86),boxH=clamp(Math.round(H*.23),90,150);const c={id,x,y,boxW,boxH,points:[],vx:0,vy:0,lost:0,good:0};c.points=seedPoints(gray,c);return c;}
function trackOne(c,prev,next){if(!c.points.length){c.lost++;c.x+=clamp(c.vx,-7,7);c.y+=clamp(c.vy,-7,7);return;}const p0=pointMat(c.points),p1=new cv.Mat(),st=new cv.Mat(),err=new cv.Mat();cv.calcOpticalFlowPyrLK(prev,next,p0,p1,st,err,new cv.Size(21,21),3,new cv.TermCriteria(cv.TERM_CRITERIA_EPS|cv.TERM_CRITERIA_COUNT,20,.03),0,.001);const good=[];for(let i=0;i<p1.rows;i++){if(st.data[i]!==1)continue;const x=p1.data32F[i*2],y=p1.data32F[i*2+1],ox=c.points[i][0],oy=c.points[i][1];if(x<0||x>=W||y<0||y>=H)continue;const dx=x-ox,dy=y-oy;if(Math.hypot(dx,dy)>35)continue;good.push([x,y,dx,dy]);}p0.delete();p1.delete();st.delete();err.delete();if(good.length<Math.max(5,Math.floor(c.points.length*.18))){c.lost++;c.good=good.length;c.x+=clamp(c.vx,-7,7);c.y+=clamp(c.vy,-7,7);c.vx*=.55;c.vy*=.55;return;}const dxs=good.map(q=>q[2]).sort((a,b)=>a-b),dys=good.map(q=>q[3]).sort((a,b)=>a-b),mdx=dxs[Math.floor(dxs.length/2)],mdy=dys[Math.floor(dys.length/2)];const inliers=good.filter(q=>Math.hypot(q[2]-mdx,q[3]-mdy)<10);if(inliers.length<5){c.lost++;return;}const mx=inliers.reduce((s,q)=>s+q[0],0)/inliers.length,my=inliers.reduce((s,q)=>s+q[1],0)/inliers.length;const ndx=mx-c.x,ndy=my-c.y,maxStep=clamp(Math.min(W,H)*.075,24,48),step=Math.hypot(ndx,ndy),k=step>maxStep?maxStep/step:1;const nx=c.x+ndx*k,ny=c.y+ndy*k;c.vx=c.vx*.65+(nx-c.x)*.35;c.vy=c.vy*.65+(ny-c.y)*.35;c.x=nx;c.y=ny;c.lost=0;c.good=inliers.length;c.points=inliers.map(q=>[q[0],q[1]]);if(c.points.length<18){const more=seedPoints(next,c);if(more.length>c.points.length)c.points=more;}}
function collisionGuard(){for(let i=0;i<copos.length;i++)for(let j=i+1;j<copos.length;j++){const a=copos[i],b=copos[j],minD=Math.max(a.boxW*.28,18),dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d<minD){const sep=minD-d;if(d<.1){a.x-=sep/2;b.x+=sep/2;}else{a.x-=dx/d*sep/2;a.y-=dy/d*sep/2;b.x+=dx/d*sep/2;b.y+=dy/d*sep/2;}}}}
function cropTemplate(gray,x,y,size){const half=Math.floor(size/2),x0=Math.round(x)-half,y0=Math.round(y)-half;if(x0<0||y0<0||x0+size>W||y0+size>H)return null;const out=new cv.Mat();gray.roi(new cv.Rect(x0,y0,size,size)).copyTo(out);return out;}
function trackPedrinha(prev,next){if(!pedra.active||!pedra.template)return;const size=pedra.size,half=Math.floor(size/2),search=clamp(Math.min(W,H)*.12,30,55);const sx=Math.round(pedra.x-search-half),sy=Math.round(pedra.y-search-half),sw=Math.min(W-sx,size+2*search),sh=Math.min(H-sy,size+2*search);if(sx<0||sy<0||sw<size||sh<size){pedra.visible=false;pedra.lost++;return;}const roi=next.roi(new cv.Rect(sx,sy,sw,sh)),result=new cv.Mat();cv.matchTemplate(roi,pedra.template,result,cv.TM_CCOEFF_NORMED);const mm=cv.minMaxLoc(result);result.delete();roi.delete();const score=mm.maxVal;const nx=sx+mm.maxLoc.x+half,ny=sy+mm.maxLoc.y+half;const maxJump=clamp(Math.min(W,H)*.09,22,42);const d=Math.hypot(nx-pedra.x,ny-pedra.y);if(!Number.isFinite(score)||score<.72||d>maxJump){pedra.visible=false;pedra.lost++;return;}pedra.x=pedra.x*.25+nx*.75;pedra.y=pedra.y*.25+ny*.75;pedra.visible=true;pedra.lost=0;pedra.lastScore=score;}
function draw(){if(!cameraAtiva)return;ctx.clearRect(0,0,canvas.width,canvas.height);const sx=canvas.width/W,sy=canvas.height/H;for(const c of copos){const x=c.x*sx,y=c.y*sy,bw=c.boxW*sx,bh=c.boxH*sy;ctx.strokeStyle="#fff";ctx.lineWidth=Math.max(3,canvas.width/260);ctx.strokeRect(x-bw/2,y-bh/2,bw,bh);ctx.fillStyle="#fff";ctx.font=`900 ${Math.max(24,canvas.width/30)}px Arial`;ctx.fillText(String(c.id),x-bw/2+5,y-bh/2-7);}if(alvoCopoId!==null){const c=copos.find(q=>q.id===alvoCopoId);if(c){const x=c.x*sx,y=(c.y+c.boxH*.32)*sy;ctx.strokeStyle="#fff";ctx.lineWidth=Math.max(4,canvas.width/200);ctx.beginPath();ctx.arc(x,y,Math.max(17,canvas.width/22),0,Math.PI*2);ctx.stroke();}}if(pedra.active&&pedra.visible){const x=pedra.x*sx,y=pedra.y*sy;ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(x,y,Math.max(7,canvas.width/65),0,Math.PI*2);ctx.fill();ctx.strokeStyle="#000";ctx.lineWidth=Math.max(2,canvas.width/300);ctx.stroke();}}
async function loop(t){if(cameraAtiva&&!busy&&copos.length===3&&t-last>=PROCESS_MS){busy=true;last=t;try{const gray=grab();if(prevGray){for(const c of copos)trackOne(c,prevGray,gray);collisionGuard();trackPedrinha(prevGray,gray);}if(prevGray)prevGray.delete();prevGray=gray;}catch(e){console.error(e);}busy=false;}draw();raf=requestAnimationFrame(loop);}
async function start(){try{await ensureCV();}catch(e){status("Não consegui carregar o motor de rastreamento. Recarregue a página.");return;}if(stream)stream.getTracks().forEach(t=>t.stop());try{stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:"environment"},width:{ideal:1280},height:{ideal:720}}});}catch(e){try{stream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});}catch(e2){status("Não consegui acessar a câmera.");return;}}video.srcObject=stream;await new Promise(r=>{if(video.readyState>=1)r();else video.onloadedmetadata=r;});dims();await video.play().catch(()=>{});cameraAtiva=true;copos=[];alvoCopoId=null;pedra={active:false,visible:false,x:0,y:0,template:null,size:25,lastScore:0,lost:0};modo="parado";if(prevGray){prevGray.delete();prevGray=null;}status("🔥 CÂMERA ATIVA. Calibre os 3 copos.");if(!raf)raf=requestAnimationFrame(loop);}
startButton.onclick=start;
calibrarButton.onclick=async()=>{if(!cameraAtiva)return status("Primeiro abra a câmera.");copos=[];alvoCopoId=null;pedra.active=false;pedra.visible=false;modo="copos";status("Toque no centro do COPO 1.");};
pedrinhaButton.onclick=()=>{if(!cameraAtiva)return status("Primeiro abra a câmera.");if(copos.length!==3)return status("Primeiro calibre os 3 copos.");modo="pedrinha";status("🪨 Quando a pedrinha estiver VISÍVEL, toque exatamente nela para colocar a bolinha branca.");};
limparButton.onclick=()=>{copos=[];alvoCopoId=null;pedra={active:false,visible:false,x:0,y:0,template:null,size:25,lastScore:0,lost:0};modo="parado";status("Marcações limpas.");};
canvas.addEventListener("pointerdown",async e=>{if(!cameraAtiva)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height;if(modo==="copos"){const gray=grab(),id=copos.length+1,c=initializeTrack(x,y,id,gray);gray.delete();if(c.points.length<8){status("Toque mais no corpo do copo, evitando a coroa.");return;}copos.push(c);if(copos.length===3){modo="parado";status("🔥 3 COPOS FIXADOS. Teste as caixas. Depois marque a pedrinha quando ela aparecer.");}else status(`Copo ${id} fixado. Toque no COPO ${id+1}.`);return;}if(modo==="pedrinha"){const gray=grab(),size=clamp(Math.round(Math.min(W,H)*.055),19,31),tpl=cropTemplate(gray,x,y,size);gray.delete();if(!tpl){status("Toque exatamente na pedrinha, deixando espaço ao redor.");return;}if(pedra.template)pedra.template.delete();pedra={active:true,visible:true,x,y,template:tpl,size,lastScore:1,lost:0};modo="parado";status("⚪ PEDRINHA MARCADA. A bolinha branca seguirá somente enquanto a pedrinha estiver visível.");return;}});
