"use strict";

/* PedrinhaTracker Web — V7
 * Rastreamento híbrido: âncoras múltiplas + template da caixa + movimento + associação global.
 * A marca PEDRINHA é somente para a pedrinha VISÍVEL perto do copo selecionado.
 * Quando a pedrinha fica ocultada, a marca some; não há reconstrução da posição oculta.
 */
const video=document.getElementById("video"), canvas=document.getElementById("canvas"), ctx=canvas.getContext("2d");
const statusEl=document.getElementById("status"), startButton=document.getElementById("start"), calibrarButton=document.getElementById("calibrar"), pedrinhaButton=document.getElementById("pedrinha"), limparButton=document.getElementById("limpar"), cameraBox=document.querySelector(".camera");
const MAX_PIXELS=110000, PROCESS_MS=45, MAX_LOST=16, ANCHOR_COUNT=9;
let W=240,H=430, boxW=54,boxH=92,searchR=52,maxJump=48,anchorR=3,redMarker=null;
const work=document.createElement("canvas"), wctx=work.getContext("2d",{willReadFrequently:true});
let stream=null,cameraAtiva=false,modo="parado",copos=[],alvoCopoId=null,trackerReady=false,lastProcess=0,raf=0,busy=false;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function status(t){statusEl.textContent=t}
function gray(data,x,y){x=clamp(Math.round(x),0,W-1);y=clamp(Math.round(y),0,H-1);let i=(y*W+x)*4,d=data.data;return .299*d[i]+.587*d[i+1]+.114*d[i+2]}
function rgb(data,x,y){x=clamp(Math.round(x),0,W-1);y=clamp(Math.round(y),0,H-1);let i=(y*W+x)*4,d=data.data;return[d[i],d[i+1],d[i+2]]}
function patch(data,cx,cy,r=anchorR){const a=[];let s=0,n=0;for(let y=-r;y<=r;y++)for(let x=-r;x<=r;x++){let v=gray(data,cx+x,cy+y);a.push(v);s+=v;n++}let m=s/n,ss=0;for(const v of a)ss+=(v-m)*(v-m);let sd=Math.sqrt(Math.max(25,ss/n));return a.map(v=>(v-m)/sd)}
function pdist(data,x,y,t,r=anchorR){if(!t)return 99;let p=patch(data,x,y,r),e=0;for(let i=0;i<p.length;i++){let q=p[i]-t[i];e+=q*q}return e/p.length}
function gradient(data,x,y){return Math.abs(gray(data,x+2,y)-gray(data,x-2,y))+Math.abs(gray(data,x,y+2)-gray(data,x,y-2))}
function makeAnchors(data,cx,cy){const offsets=[[-.32,-.36],[0,-.38],[.32,-.36],[-.36,-.05],[0,-.05],[.36,-.05],[-.30,.30],[0,.30],[.30,.30]], out=[];for(const[oX,oY]of offsets){let x=Math.round(cx+oX*boxW),y=Math.round(cy+oY*boxH);if(x<8||y<8||x>=W-8||y>=H-8)continue;out.push({ox:oX,oy:oY,ref:patch(data,x,y),x,y,good:1})}return out}
function fullTemplate(data,cx,cy){const vals=[];let s=0,n=0;for(let y=-boxH*.45;y<=boxH*.45;y+=4)for(let x=-boxW*.45;x<=boxW*.45;x+=4){let v=gray(data,cx+x,cy+y);vals.push(v);s+=v;n++}let m=s/n,ss=0;for(const v of vals)ss+=(v-m)*(v-m);let sd=Math.sqrt(Math.max(25,ss/n));return vals.map(v=>(v-m)/sd)}
function fullScore(data,cx,cy,t){if(!t)return 99;const vals=[];let s=0,n=0;for(let y=-boxH*.45;y<=boxH*.45;y+=4)for(let x=-boxW*.45;x<=boxW*.45;x+=4){let v=gray(data,cx+x,cy+y);vals.push(v);s+=v;n++}let m=s/n,ss=0;for(const v of vals)ss+=(v-m)*(v-m);let sd=Math.sqrt(Math.max(25,ss/n));let e=0;for(let i=0;i<vals.length;i++){let q=(vals[i]-m)/sd-t[i];e+=q*q}return e/n}
function trackAnchors(data,c){const px=clamp(c.x+c.vx,boxW/2+3,W-boxW/2-3),py=clamp(c.y+c.vy,boxH/2+3,H-boxH/2-3), moves=[];for(const a of c.anchors){const bx=a.x+(px-c.x),by=a.y+(py-c.y);let best=null;for(let dy=-18;dy<=18;dy+=2)for(let dx=-18;dx<=18;dx+=2){let x=Math.round(bx+dx),y=Math.round(by+dy);if(x<5||y<5||x>=W-5||y>=H-5)continue;let d=pdist(data,x,y,a.ref);if(!best||d<best.d)best={x,y,d}}if(best&&best.d<1.75)moves.push({dx:best.x-a.x,dy:best.y-a.y,d:best.d})}if(moves.length<3)return{x:px,y:py,q:moves.length/c.anchors.length,moves:[]};const med=(arr)=>{arr=arr.slice().sort((a,b)=>a-b);return arr[Math.floor(arr.length/2)]};let mdx=med(moves.map(m=>m.dx)),mdy=med(moves.map(m=>m.dy));let inl=moves.filter(m=>Math.hypot(m.dx-mdx,m.dy-mdy)<=6);let dx=med(inl.map(m=>m.dx)),dy=med(inl.map(m=>m.dy));return{x:clamp(c.x+dx,boxW/2+3,W-boxW/2-3),y:clamp(c.y+dy,boxH/2+3,H-boxH/2-3),q:inl.length/c.anchors.length,moves:inl}}
function candidates(data,c,m){const r=clamp(searchR+c.lost*3,44,72),list=[];for(let y=Math.round(m.y-r);y<=m.y+r;y+=4)for(let x=Math.round(m.x-r);x<=m.x+r;x+=4){if(x<boxW/2+2||y<boxH/2+2||x>W-boxW/2-2||y>H-boxH/2-2)continue;let dist=Math.hypot(x-m.x,y-m.y),jump=Math.hypot(x-c.x,y-c.y);if(dist>r||jump>maxJump+c.lost*5)continue;let fs=fullScore(data,x,y,c.template);if(fs>4.2)continue;let score=fs+dist*.012+jump*.018-m.q*.65;list.push({x,y,score,fs})}list.sort((a,b)=>a.score-b.score);return list.slice(0,6)}
function permute(a){const p=[[0,1,2],[0,2,1],[1,0,2],[1,2,0],[2,0,1],[2,1,0]];let best=null;for(const q of p){const r=q.map((j,i)=>a[i][j]);if(r.some(v=>!v))continue;const ds=[Math.hypot(r[0].x-r[1].x,r[0].y-r[1].y),Math.hypot(r[0].x-r[2].x,r[0].y-r[2].y),Math.hypot(r[1].x-r[2].x,r[1].y-r[2].y)];if(Math.min(...ds)<boxW*.48)continue;let score=r.reduce((s,v)=>s+v.score,0);if(!best||score<best.score)best={r,score}}return best}
function init(c,data){c.template=fullTemplate(data,c.x,c.y);c.anchors=makeAnchors(data,c.x,c.y);c.vx=0;c.vy=0;c.lost=0;c.conf=1}
function update(data){if(!trackerReady){coposInit(data);return}const motions=copos.map(c=>trackAnchors(data,c)),cand=copos.map((c,i)=>candidates(data,c,motions[i])),best=permute(cand);for(let i=0;i<3;i++){const c=copos[i],m=motions[i],q=best?.r[i];if(!q){c.lost++;c.conf=Math.max(0,c.conf-.08);c.x=m.x;c.y=m.y;c.vx*=.82;c.vy*=.82;continue}let jump=Math.hypot(q.x-c.x,q.y-c.y);if(jump>maxJump+Math.min(c.lost,5)*5){c.lost++;c.conf=Math.max(0,c.conf-.1);c.x=m.x;c.y=m.y;c.vx*=.82;c.vy*=.82;continue}let a=c.lost?.78:.62,nx=c.x*(1-a)+q.x*a,ny=c.y*(1-a)+q.y*a;c.vx=c.vx*.30+(nx-c.x)*.70;c.vy=c.vy*.30+(ny-c.y)*.70;c.x=nx;c.y=ny;c.lost=0;c.conf=Math.min(1,c.conf+.06*m.q);if(m.moves.length>=3){for(const mv of m.moves){let target=c.anchors.reduce((b,p)=>{let d=Math.hypot(p.x-(c.x+mv.dx),p.y-(c.y+mv.dy));return !b||d<b.d?{p,d}:b},null);if(target&&target.d<14){target.p.x=c.x+mv.dx;target.p.y=c.y+mv.dy}}}if(c.lost===0){let fresh=fullTemplate(data,c.x,c.y);for(let k=0;k<c.template.length;k++)c.template[k]=c.template[k]*.995+fresh[k]*.005}}detectMarker(data)}
function coposInit(data){copos.forEach(c=>init(c,data));trackerReady=true}
function detectMarker(data){redMarker=null;if(alvoCopoId==null)return;const c=copos.find(v=>v.id===alvoCopoId);if(!c)return;const x0=Math.round(c.x-boxW*.62),x1=Math.round(c.x+boxW*.62),y0=Math.round(c.y+boxH*.28),y1=Math.round(c.y+boxH*1.15);let best=null;for(let y=y0;y<=y1;y+=2)for(let x=x0;x<=x1;x+=2){const[r,g,b]=rgb(data,x,y),mx=Math.max(r,g,b),mn=Math.min(r,g,b);if(r>95&&r>g*1.45&&r>b*1.35&&(r-g)>35){let score=r-g*.5-b*.2;if(!best||score>best.score)best={x,y,score}}}if(!best)return;let cx=best.x,cy=best.y;let count=0,sx=0,sy=0;for(let y=Math.max(y0,cy-12);y<=Math.min(y1,cy+12);y+=2)for(let x=Math.max(x0,cx-16);x<=Math.min(x1,cx+16);x+=2){const[r,g,b]=rgb(data,x,y);if(r>95&&r>g*1.45&&r>b*1.35){sx+=x;sy+=y;count++}}if(count<5)return;redMarker={x:sx/count,y:sy/count}}
function draw(){if(!cameraAtiva)return;ctx.clearRect(0,0,canvas.width,canvas.height);let sx=canvas.width/W,sy=canvas.height/H,lw=Math.max(3,canvas.width/250);for(const c of copos){let x=c.x*sx,y=c.y*sy,bw=boxW*1.25*sx,bh=boxH*1.25*sy;ctx.strokeStyle="#fff";ctx.lineWidth=lw;ctx.strokeRect(x-bw/2,y-bh/2,bw,bh);ctx.fillStyle="#fff";ctx.font=`900 ${Math.max(24,canvas.width/30)}px Arial`;ctx.fillText(c.id,x-10,y-bh/2-8)}if(redMarker&&alvoCopoId!=null){let x=redMarker.x*sx,y=redMarker.y*sy;ctx.strokeStyle="#fff";ctx.lineWidth=Math.max(5,canvas.width/180);ctx.beginPath();ctx.arc(x,y,Math.max(18,Math.min(canvas.width,canvas.height)/18),0,Math.PI*2);ctx.stroke();ctx.fillStyle="#fff";ctx.font=`900 ${Math.max(14,canvas.width/52)}px Arial`;ctx.fillText("PEDRINHA",x-50,y-26)}}
function frame(){if(!video.videoWidth)return null;wctx.drawImage(video,0,0,W,H);return wctx.getImageData(0,0,W,H)}
function loop(t){if(cameraAtiva&&!busy&&t-lastProcess>=PROCESS_MS&&copos.length===3){busy=true;lastProcess=t;let f=frame();if(f)update(f);busy=false}draw();raf=requestAnimationFrame(loop)}
function prep(){video.muted=true;video.autoplay=true;video.playsInline=true;video.setAttribute("playsinline","");video.setAttribute("webkit-playsinline","");video.setAttribute("autoplay","");video.setAttribute("muted","")}
function dims(){if(!video.videoWidth)return;let s=Math.min(1,Math.sqrt(MAX_PIXELS/(video.videoWidth*video.videoHeight)));W=Math.max(180,Math.round(video.videoWidth*s));H=Math.max(180,Math.round(video.videoHeight*s));boxW=clamp(Math.round(W*.20),40,58);boxH=clamp(Math.round(H*.115),64,100);searchR=clamp(Math.round(Math.min(W,H)*.14),42,70);maxJump=clamp(Math.round(Math.min(W,H)*.12),36,58);work.width=W;work.height=H;canvas.width=video.videoWidth;canvas.height=video.videoHeight;cameraBox.style.aspectRatio=`${video.videoWidth}/${video.videoHeight}`}
async function start(){prep();status("Solicitando acesso à câmera...");if(!navigator.mediaDevices?.getUserMedia)return status("Este navegador não disponibiliza a câmera.");if(stream)stream.getTracks().forEach(t=>t.stop());try{stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:"environment"},width:{ideal:1280},height:{ideal:720}}})}catch(e){try{stream=await navigator.mediaDevices.getUserMedia({video:true,audio:false})}catch(e2){return status("Não consegui acessar a câmera.")}}video.srcObject=stream;await new Promise(r=>video.readyState>=1?r():video.onloadedmetadata=r);dims();try{await video.play()}catch(e){}cameraAtiva=true;trackerReady=false;status("🔥 CÂMERA ATIVA! Calibre os 3 copos.");if(!raf)raf=requestAnimationFrame(loop)}
startButton.onclick=start;
calibrarButton.onclick=()=>{if(!cameraAtiva)return status("Primeiro toque em ABRIR CÂMERA.");copos=[];alvoCopoId=null;redMarker=null;trackerReady=false;modo="copos";status("Toque no centro do COPO 1.")};
pedrinhaButton.onclick=()=>{if(!cameraAtiva)return status("Primeiro abra a câmera.");if(copos.length!==3)return status("Primeiro calibre os 3 copos.");modo="alvo";status("Toque no copo que deve receber a marca PEDRINHA visível.")};
limparButton.onclick=()=>{copos=[];alvoCopoId=null;redMarker=null;trackerReady=false;modo="parado";status("Marcações limpas.")};
canvas.addEventListener("pointerdown",e=>{if(!cameraAtiva)return;let r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height;if(modo==="copos"){let id=copos.length+1;copos.push({id,x,y,vx:0,vy:0,lost:0,conf:1,template:null,anchors:[]});status(copos.length===3?"🔥 3 copos calibrados. Agora fixe a PEDRINHA em um deles.":`Copo ${id} marcado. Agora toque no copo ${id+1}.`);if(copos.length===3)modo="parado"}else if(modo==="alvo"){let best=copos.reduce((b,c)=>{let d=Math.hypot(c.x-x,c.y-y);return !b||d<b.d?{c,d}:b},null);if(!best||best.d>Math.max(boxW,boxH)*.7)return status("Toque dentro de um dos copos.");alvoCopoId=best.c.id;modo="parado";status(`🔥 PEDRINHA vinculada ao COPO ${best.c.id}. Só a pedrinha visível próxima dele será marcada.`)}});
prep();status("Pronto. Toque em ABRIR CÂMERA.");
  
